[parity]
chain = "ethereum"
mode = "active"
base_path = "/openethereum"

[rpc]
interface = "all"
cors = ["*"]
hosts = ["all"]
apis = ["web3", "eth", "pubsub", "net", "parity", "private", "parity_pubsub", "traces", "rpc", "parity_transactions_pool"]
server_threads = 16
port = 8545

[websockets]
interface = "all"
hosts = ["all"]
origins = ["*"]
apis = ["web3", "eth", "pubsub", "net", "parity", "private", "parity_pubsub", "traces", "rpc", "parity_transactions_pool"]
port = 8546

[footprint]
tracing = "off"
db_compaction = "ssd"
pruning = "fast"
cache_size = 8000

[network]
no_serve_light = true